version: "3.2"
services:
  sql-server-db:
    restart: always
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "ch@allegneN5_password"
      ACCEPT_EULA: "Y"
    volumes:
       - "./database/initDb.sql:/docker-entrypoint-initdb.d/initDb.sql"

  challenge-api:
    restart: always
    container_name: challenge-api
    build:
      context: ../
      dockerfile: ChallengeN5.Api/Dockerfile
    ports:
      - "8080:80"

  elasticsearch:
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    
  kafka:
    restart: always
    image: confluentinc/cp-kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  
  kibana:
    restart: always
    image: docker.elastic.co/kibana/kibana:7.11.0
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch:9200"